# Generated by Django 5.2.13 on 2026-04-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('app_name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('short_video', '短视频'), ('social', '社交'), ('study', '学习'), ('tool', '工具'), ('video_music', '视频音乐'), ('game', '游戏'), ('shopping', '购物'), ('other', '其他')], default='other', max_length=32)),
                ('purpose_group', models.CharField(choices=[('entertainment', '娱乐'), ('social', '社交'), ('study', '学习'), ('life', '生活')], default='life', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['package_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_duration_sec', models.PositiveIntegerField(default=0)),
                ('launch_count', models.PositiveIntegerField(default=0)),
                ('night_duration_sec', models.PositiveIntegerField(default=0)),
                ('longest_session_sec', models.PositiveIntegerField(default=0)),
                ('entertainment_ratio', models.FloatField(default=0.0)),
                ('social_ratio', models.FloatField(default=0.0)),
                ('study_ratio', models.FloatField(default=0.0)),
                ('life_ratio', models.FloatField(default=0.0)),
                ('switch_count', models.PositiveIntegerField(default=0)),
                ('top_app_name', models.CharField(blank=True, max_length=128)),
                ('top_app_ratio', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_usage_aggregate')],
            },
        ),
        migrations.CreateModel(
            name='UsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('short_video', '短视频'), ('social', '社交'), ('study', '学习'), ('tool', '工具'), ('video_music', '视频音乐'), ('game', '游戏'), ('shopping', '购物'), ('other', '其他')], default='other', max_length=32)),
                ('purpose_group', models.CharField(choices=[('entertainment', '娱乐'), ('social', '社交'), ('study', '学习'), ('life', '生活')], default='life', max_length=32)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_sec', models.PositiveIntegerField()),
                ('is_night_session', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('android', 'Android'), ('sample', 'Sample')], default='android', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='usage_usage_user_id_911617_idx'), models.Index(fields=['device', 'start_time'], name='usage_usage_device__aabbd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device', 'package_name', 'start_time', 'end_time'), name='unique_usage_session')],
            },
        ),
    ]
