# Generated by Django 5.2.13 on 2026-04-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rule_score', models.FloatField(default=0.0)),
                ('ml_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=16)),
                ('reason_summary', models.TextField(blank=True)),
                ('top_reasons_json', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(default='rule_engine', max_length=64)),
                ('model_version', models.CharField(default='builtin', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_risk_result_per_day')],
            },
        ),
        migrations.CreateModel(
            name='WarningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_time', models.DateTimeField()),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=16)),
                ('trigger_type', models.CharField(default='daily_analysis', max_length=32)),
                ('reason_text', models.TextField()),
                ('action_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_records', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-warning_time'],
                'indexes': [models.Index(fields=['user', 'warning_time'], name='warnings_wa_user_id_ca18d2_idx')],
            },
        ),
    ]
